<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Major;

class MajorSeeder extends Seeder
{
    public function run(): void
    {
        $majors = [

            // 🔹 Tech & IT
            'Computer Science',
            'Software Engineering',
            'Data Science',
            'Artificial Intelligence',
            'Cybersecurity',
            'Information Systems',
            'Information Technology',
            'Information and Documentation',
            'Information Communications Technology',
            'IT Management',
            'Business Informatics',
            'Computer Science for Business',
            'Web Science and Digital Economics and Banks and Financial Markets',
            'Computer Graphics and Interactive Media',
            'Computer Vision',
            'Data Engineering',
            'Computer Communication Engineering',
            'Interactive Communication',
            'Video Game Development',
            'Internet of Things',
            'Formal Methods in Computer Engineering',
            'Computer Engineering',
            'Computer Engineering and Telecommunication Systems Engineering',
            'Computer Engineering Telecommunication and Electronic Engineering',
            'Communication Engineering',
            'Telecommunication Systems Engineering',
            'Telecommunications Engineering',
            'Electronic Engineering for Telecommunication',
            'Electronic Communications Engineering',
            'Systems and Control Engineering',
            'Engineering Renewable Energies Energy Efficiency',
            'Information Technology and Services',
            
            // 🔹 Engineering
            'Electrical Engineering',
            'Electrical and Electronics Engineering',
            'Mechanical Engineering',
            'Civil Engineering',
            'Chemical Engineering',
            'Industrial Engineering',
            'Biomedical Engineering',
            'Aerospace Engineering',
            'Mechatronics Engineering',
            'Materials Engineering',
            'Petroleum Engineering',
            'Environmental Engineering',
            'Geological Engineering',
            'Mathematical Engineering',
            'Automation and Industrial Electronic Engineering',
            'Automation and Industrial Electronic Engineering and Mechanical Engineering',
            'Automotive Engineering',
            'Engineering in Industrial Organisation',
            'Energy',
            'Disaster Management',
            'New Electronic and Photonic Technologies',

            // 🔹 Science
            'Mathematics',
            'Applied Mathematics',
            'Applied Statistics',
            'Statistics',
            'Computational Mathematics and Data Analytics',
            'Physics',
            'Physics and Chemistry',
            'Physics and Mathematics',
            'Chemistry',
            'Chemistry and Biochemistry',
            'Green and Sustainable Chemistry',
            'Biochemistry',
            'Biochemistry, Molecular Biology and Biomedicine',
            'Biology',
            'Biotechnology',
            'Biomedical Sciences',
            'Neuroscience',
            'Neuroengineering and Rehabilitation',
            'Molecular Biology',
            'Molecular Life Sciences',
            'Molecular Medicine',
            'Nanoscience',
            'Nanophysics and Advanced Materials',
            'Microbiology',
            'Advanced Microbiology',
            'Cytogenetics and Reproductive Biology',
            'DNA Technology',
            'Genetics',
            'Genetics and Cell Biology',
            'Neurosciences',
            'Health Data Science',
            'Bioinformatics',
            'Environmental Technologies',
            'Environmental Science and Geology',
            'Environmental Sciences',
            'Environmental Biology',
            'Food Science and Technology',
            'Nutrition and Food Science',
            'Human Nutrition and Dietetics',
            'Nutrition',
            'Biomedicine',
            'Optics Optometry',
            'Optics and Optometry',
            'Radiological Sciences',
            'Forensic Science',
            'Bio Analytic Toxicology',
            'Pharmacology',
            'Pharmacovigilance and Pharmacoepidemiology',
            'Physiotherapy of the Thorax',
            'Neurodevelopmental Disorders and Mental Health',
            'Neurological Disorders and Disabilities',
            'Psychology',
            'Clinical Psychology',
            'Psychology of Sport and Physical Activity',
            'Psychosocial Research and Intervention',
            'Educational Psychology',
            'Research in Clinical Psychology and Health',
            'Cognitive Science and Language',
            'Applied Clinical Research in Health Sciences',
            'Translational Research in Physiotherapy',
            'Translational Biomedical Research',
            'Zoonoses and One Health',
            'Erasmus Mundus in Infectious Diseases and One Health',
            'Erasmus Mundus in Health Management in Aquaculture',
            'Applied Microbiology',
            'Applied Ethics',
            'Aquaculture',
            'Drug Discovery',
            'Food Safety',
            'Quality of Food of Animal Origin',
            'Sanitary Biology',
            'Virology',
            'Zoology',
            'Paleobiology and Fossil Record',
            'Advanced Genetics',
            'Advanced Biotechnology',
            'Advanced Immunology',
            'Animal Genetics and Breeding, and Reproductive Biotechnology',

            // 🔹 Medical & Health
            'Medicine',
            'Medical Doctor',
            'Dentistry',
            'Doctor of Dental Surgery',
            'Pharmacy',
            'Doctor Of Pharmacy',
            'Pharmacy and Pharmaceutical Technology',
            'Nursing',
            'Nursing Sciences',
            'Nursing Innovation Applied to Vulnerability and Health',
            'Public Health',
            'Medical Laboratory Analysis',
            'Clinical Laboratory Science',
            'Physiotherapy',
            'Occupational Therapy',
            'Speech Therapy',
            'Speech and Language Therapy',
            'Podiatry',
            'Optometry and Vision',
            'Dental Sciences',
            'Medical Surgical Nursing',
            'Critical Care Nursing',
            'Human Anatomy and Embryology',
            'Medical Physiology',
            'Endodontology',
            'Operative and Esthetic Dentistry',
            'Oral Surgery',
            'Orthodontics',
            'Pediatric Dentistry',
            'Periodontology',
            'Prosthodontics and Esthetic Dentistry',
            'Pharmaceutical and Biological Sciences',
            'Pharmaceutical Marketing',
            'Biomedical Physics',
            'Chemistry and Biochemistry for Health',
            'Hospital Clinical Optometry',
            'Health Care Research',
            'Health, Integration and Disability',
            'Occupational Risk Prevention',
            'Research in Translational Medicine',
            'Research in Vision Sciences',
            'Introduction to Research in Mental Health',
            'Legal and Forensic Psychology',
            'Neurorehabilitation',
            'General Health Psychology',
            'Nursing Innovation Applied to Vulnerability and Health',

            // 🔹 Business & Economics
            'Economics',
            'Economics and Mathematics and Statistics',
            'Finance',
            'Accounting',
            'Business Administration',
            'Business Administration and Management',
            'Business and Information Technology',
            'Management',
            'Management Information Systems',
            'Marketing',
            'Business Finance',
            'Banking and Quantitative Finance',
            'Business Management, Marketing and Accounting Research',
            'Business Marketing',
            'Financial Engineering',
            'Entrepreneurship and Social Innovation',
            'International Business',
            'Human Resources Management',
            'Digital Marketing',
            'Marketing Communication',
            'Business Research',
            'Economic Analysis',
            'Applied Research in Economics and Business',
            'Erasmus Mundus Models and Methods of Quantitative Economics',
            'Account Auditing and Accounting',
            'Audit and Accounting',
            'Actuarial and Financial Mathematics',
            'Actuarial and Financial Sciences',
            'Specialized Economic Analysis',
            'Finance, Banking and Insurance',
            'Management, Organization and Business Economics',
            'Business Administration and Management Law',
            'Law and Business Administration and Management',
            'Law and Labor Relations and Human Resources',

            // 🔹 Law
            'Law',
            'Business Law',
            'Private Law',
            'Public Law',
            'Law Degree',
            'Criminology',
            'Criminology and Law',
            'Diplomacy and International Security',
            'International Contracts',
            'International and Comparative Law',
            'Access to the Lawyer Profession',
            'Enterprise Law',
            'Advanced Studies in Financial and Tax Law',
            'Advanced Studies in Labor and Employment',
            'Advanced Studies in Political Communication',

            // 🔹 Humanities & Arts
            'Arabic Language and Literature',
            'English Language and Literature',
            'French Language and Literature',
            'Spanish Language and Literature',
            'French Language and Culture',
            'English Studies',
            'English and Catalan',
            'English and Classics',
            'English and French',
            'English and Spanish',
            'Catalan Philology',
            'Catalan and Spanish',
            'Translation',
            'Translation and Interpretation',
            'Translation and Intercultural Studies',
            'Audiovisual Translation',
            'Languages and Translation',
            'Modern Language and Literature',
            'Literary Translation',
            'Classical Philology',
            'Philosophy',
            'Analytic Philosophy',
            'Philosophy, Politics and Economics',
            'Applied Ethics',
            'Ancient Studies',
            'Ancient Mediterranean',
            'Contemporary History',
            'History',
            'History of Science',
            'History of Contemporary Art and Visual Culture',
            'History and Anthropology of America',
            'History of the Hispanic Monarchy',
            'Medieval Studies',
            'Medieval European Identity',
            'Visual Arts and Education',
            'Art Education in Social and Cultural Institutions',
            'Art and Design',
            'Design',
            'Design of Spaces',
            'Graphic Design',
            'Interior Design',
            'Fashion Design',
            'Fine Arts',
            'Music',
            'Musicology',
            'Performing Arts',
            'Theatre Studies',
            'Theater and Performing Arts',
            'Cinema and Television',
            'Audiovisual Communication',
            'Audiovisual Communication and Advertising Contents',
            'Digital Advertising',
            'Journalism',
            'Journalism and Communication',
            'Journamlism',
            'E-Journalism and E-Communication',
            'Communication Arts',
            'Communication in Organisations',
            'Public Relations',
            'Radio and Television',
            'Media, Communication and Culture',
            'Communication and Visual Arts',
            'Digital Media',
            'Cultural Heritage Conservation',
            'Conservation, Restoration of Cultural Property & Sacred Art',
            'Conservation and Restoration of Cultural Heritage',
            'Analysis and Management of the Artistic Heritage',
            'Research in Art and Design',
            'Research in Art and Creation',
            'Creative Writing',
            'Digital Humanities and Heritage',
            'Written Historical Heritage',
            'Smart and Sustainable Cities',
            'Management of Smart and Sustainable Cities',
            'European Integration',
            'Erasmus Mundus in Education Policies for Global Development',
            'Erasmus Mundus in Public Policy',
            'History of Contemporary Art and Visual Culture',

            // 🔹 Education
            'Education',
            'Administration of Education',
            'Technology of Education',
            'Education Studies',
            'Pedagogy',
            'Early Childhood Education',
            'Primary Education',
            'Teacher in Early Childhood Education',
            'Teacher in Primary Education',
            'Teacher in Early Childhood Education and Pedagogy',
            'Teacher in Early Childhood Education and Teacher in Primary Education',
            'Teacher in Primary Education and Pedagogy',
            'School Leadership for Educational Innovation',
            'School Library and Reading Promotion',
            'Research in Education',
            'Educational Psychology',
            'Education with an emphasis in Instructional Design and Technology',
            'Teaching Chinese to Spanish Speakers',
            
            // 🔹 Tourism & Hospitality
            'Tourism',
            'Tourism and Commerce',
            'Tourism Management in Cultural Heritage',
            'Hotel Management',
            'Hospitality Management',
            'International Affairs',
            'International Relations',
            'International Relations, Security and Development',
            'International Development',
            'Diplomacy and International Security',

            // 🔹 Sports
            'Sports Management',

            // 🔹 Misc / Others
            'Applied Sociology',
            'Social Work',
            'Social and Labour Rights',
            'Social Policy and Community Action',
            'Social Policy, Employment and Welfare',
            'Social Education',
            'Social and Cultural Anthropology',
            'Youth and Society',
            'Women, Gender and Citizenship Studies',
            'Semitic and Islamic Studies',
            'Religious Sciences',
            'Sciences of Religions',
            'Intervention and Social Work',
            'Care Philosophies',
            'Anthropology',
            'Archival Studies and Information Governance',
        ];

        
        $trendyMajors = [
            'Artificial Intelligence',
            'Data Science',
            'Cybersecurity',
            'Software Engineering',
            'Computer Science',
            'Information Technology',
        ];

        foreach (array_unique($majors) as $major) {
            Major::create([
                'name' => trim($major),
                'is_trendy' => in_array($major, $trendyMajors)
            ]);
        }
    }
}